### ISSUE TITLE
jpm build step fails in "Building from source once..." instructions

### ISSUE THREAD

**Issue by sogaiu** [andrewchambers/hermes#32]
The jpm build step in [Building from source once you already have hermes installed](https://github.com/andrewchambers/hermes/blob/master/doc/installing.md#building-from-source-once-you-already-have-hermes-installed) fails here with:
```
$ jpm build
error: could not load native /home/user/src/hermes/janet_modules/_process.so: Error relocating /home/user/src/hermes/janet_modules/_process.so: __snprintf_chk: symbol not found
  in native
  in <anonymous> [boot.janet] on line 2228, column 26
  in require [boot.janet] on line 2250, column 18
  in import* [boot.janet] on line 2262, column 15
  in _thunk [/home/user/src/hermes/janet_modules/process.janet] (tailcall) on line 1, column 1
...
```

I attempted the following steps (more than once with similar results):

* [Installing from source](https://github.com/andrewchambers/hermes/blob/master/doc/installing.md#installing-from-source)
* ensure there is a HERMES_STORE and run `hermes init`
* [Building from source once you already have hermes installed](https://github.com/andrewchambers/hermes/blob/master/doc/installing.md#building-from-source-once-you-already-have-hermes-installed)

The system used was Ubuntu 19.10 and Janet was 1.9.0-dev-761ea65.

**Comment by sogaiu** [comment]
I think the main cause of this is reusing the content of janet_modules -- some of its content derives from the underlying system's gcc via the [Installing from source](https://github.com/andrewchambers/hermes/blob/master/doc/installing.md#installing-from-source) step.

I tried emptying janet_modules before the `jpm load-lockfile lockfile.jdn` step in the [Building from source once you already have hermes installed](https://github.com/andrewchambers/hermes/blob/master/doc/installing.md#building-from-source-once-you-already-have-hermes-installed) section, and this seemed to resolve the issue.  Presumably it is because the relevant bits in `janet_modules` have been generated using hermes' compiler (so-to-speak) instead of that of the system.

Verified with both an Ubuntu and Manjaro system.

**Comment by andrewchambers** [comment]
Yeah that seems right. We can close this once we update the guide to make that clear, or put the janet modules into the hermes env.

**Comment by sogaiu** [comment]
Sounds good.

**Comment by andrewchambers** [comment]
Now the janet modules are part of the dev-env.hpkg, I think we can close this one.
